### PR TITLE
Fixes undefined Property errors

### PR DESCRIPTION
**Pull request by MathieuMaas**
Fixes the error: Undefined property: stdClass::$gemeentenaam and Undefined property: stdClass::$provincienaam

### CODE REVIEW

**Comment by barryvdh** [comment]
This seems to happen when we get a `postcode` type, instead of `adres`. Should perhaps the adres have a higher priority then the postcode?

**Comment by bbrala** [comment]
Thanks for the PR! Being a bit defensive on the properties seems like a good idea. We prefer you use the PR template though so we know what is covered in a glance.

@barryvdh The perfect priorities are hard, but still it shouldn't really break. Guess we should extend the tests to at least also test the different result types.

**Review by JaZo — APPROVED** [review]

**Comment by JaZo** [comment]
@MathieuMaas, thanks for the PR, looks good to me!

@barryvdh, the priorities are indeed hard to set right for every situation. I have tried many values and the current values seem to give the best results in my tests. I have even tried to set the priority of an address to 10 and it still gives a postalcode as first result while the second is an address... The development team of PDOK knows the matching and sorting is not optimal and is working on an improved (v4) version.

**Comment by JaZo** [comment]
N.B. The missing data is caused by the recent municipal reclassifications: https://geoforum.nl/t/bij-bepaalde-adressen-wordt-er-geen-woonplaats-informatie-meer-meegestuurd/2283

**Pull request merged**
